#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting emoncms domain)
path=$(sudo yunohost app setting emoncms path)
ip=$(sudo yunohost app setting emoncms server)

# Remove trailing "/" for next commands
path=${path%/}

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@IPTOCHANGE@$ip@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/emoncms.conf
sudo service nginx reload
